### PR TITLE
Update Readme add Figma UI link

### PR DESCRIPTION
**Pull request by DirwaVIP**
image

### CODE REVIEW

**Comment by pahrizal** [comment]
@DirwaVIP learn how to write a link in `README.md`.

`.md` file means its a markdown language. Search how to write a link in markdown

**Comment by DirwaVIP** [comment]
image


@pahrizal Like This?

**Comment by pahrizal** [comment]
> image
> 
> 
> 
> 
> 
> @pahrizal Like This?

Yes, cool! Good job

**Review by pahrizal — APPROVED** [review]
Well done! 🎉

**Pull request merged**
